### PR TITLE
add project website link + readme updates

### PR DESCRIPTION
**Pull request by JasonBarahan**
## Description 
Add project website link; update README.md file (mark as to-do)

## Details
I've added a (quickly-assembled) project website in case interested hiring staff, prospective employers, or other people wish to comb through our work in a more high-level manner. I will update the README.md file to reflect most website content accordingly.

The site also includes a demonstration slideshow to show how the program would run, considering that this program requires an API key to function correctly (and also because the API key is restricted by Metrolinx).

Of course, your GitHub profiles and LinkedIn profiles (if applicable) are linked in the webpage footer. Let me know if there's any changes needed.

### CODE REVIEW

**Review by carmen-chau — COMMENTED** [review]
@JasonBarahan 

The presentation looks good, added a comment regarding how the developers can be reached.

We should probably discuss about this proposed change as a group instead of discussing it through Github comments. Just making sure everyone is aware of this change, and has their permission given to share certain social media.

UPDATE: Conversation has been resolved :), feel free to ignore this comment

**Review by carmen-chau — APPROVED** [review]
Based on conversations in group chat, I'm going to go ahead and approve this

**Review by jacqnnn — APPROVED** [review]
👍

**Review by arandaaron04 — APPROVED** [review]
Approved

**Pull request merged**
